on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "Login to ghcr"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and push image"
      run: |-
        docker build . --tag ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{  github.repository }}:latest
